// 自动生成，别手改：改上游目录后跑 node tools/gen-provider-presets.mjs 重新生成
// 来源：DSH 的 provider 目录（dsh-provider-hub/core/providers.js），生成于 2026-10-03
// 归一化：reasoningEfforts 的 off 键改成 none；xhigh / minimal / ultra 等我们系统没有的档位丢掉
// 已剔除：有国内版对应的「国际版」（moonshot-global / zai / stepfun-step-plan-global / qwen-token-plan-global / minimax-coding-plan / xiaomi-token-plan-sgp / xiaomi-token-plan-ams）

export type PresetApi = "openai-completions" | "anthropic-messages" | "openai-responses"

export interface PresetModel {
  id: string
  name: string
  /** 可用推理档位 → 请求里实际发出去的值 */
  efforts?: Record<string, string>
}

export interface PresetProvider {
  id: string
  name: string
  baseUrl: string
  api: PresetApi
  docs?: string
  keyUrl?: string
  models: PresetModel[]
}

export const PROVIDER_PRESETS: PresetProvider[] = [
  {
    id: "openai",
    name: "OpenAI",
    baseUrl: "https://api.openai.com/v1",
    api: "openai-completions",
    docs: "https://platform.openai.com/docs/models",
    keyUrl: "https://platform.openai.com/api-keys",
    models: [
    { id: "gpt-6-astra", name: "GPT-6 Astra", efforts: {"low":"low","medium":"medium","high":"high","max":"max"} },
    { id: "gpt-5.6-luna", name: "GPT-5.6 Luna", efforts: {"none":"none","low":"low","medium":"medium","high":"high","max":"max"} },
    { id: "gpt-5.6-sol", name: "GPT-5.6 Sol", efforts: {"none":"none","low":"low","medium":"medium","high":"high","max":"max"} },
    { id: "gpt-5.6-terra", name: "GPT-5.6 Terra", efforts: {"none":"none","low":"low","medium":"medium","high":"high","max":"max"} },
    { id: "gpt-5.5-pro", name: "GPT-5.5 Pro", efforts: {"medium":"medium","high":"high"} },
    { id: "gpt-5.5", name: "GPT-5.5", efforts: {"none":"none","low":"low","medium":"medium","high":"high"} },
    ],
  },
  {
    id: "openrouter",
    name: "OpenRouter",
    baseUrl: "https://openrouter.ai/api/v1",
    api: "openai-completions",
    docs: "https://openrouter.ai/models",
    keyUrl: "https://openrouter.ai/keys",
    models: [
    { id: "anthropic/claude-opus-5", name: "Claude Opus 5", efforts: {"low":"low","medium":"medium","high":"high","max":"max"} },
    { id: "openai/gpt-5.6-sol", name: "OpenAI: GPT-5.6 Sol", efforts: {"none":"none","low":"low","medium":"medium","high":"high","max":"max"} },
    { id: "x-ai/grok-4.6", name: "SpaceXAI: Grok 4.6", efforts: {"low":"low","medium":"medium","high":"high"} },
    { id: "moonshotai/kimi-k3", name: "MoonshotAI: Kimi K3", efforts: {"none":"none","low":"low","high":"high","max":"max"} },
    { id: "qwen/qwen3.8-max", name: "Qwen: Qwen3.8 Max", efforts: {"low":"low","medium":"medium","high":"high"} },
    ],
  },
  {
    id: "anthropic",
    name: "Anthropic (Messages API)",
    baseUrl: "https://api.anthropic.com",
    api: "anthropic-messages",
    docs: "https://docs.anthropic.com/en/docs/about-claude/models",
    keyUrl: "https://console.anthropic.com/settings/keys",
    models: [
    { id: "claude-fable-5-1", name: "Claude Fable 5.1", efforts: {"max":"max"} },
    { id: "claude-fable-5", name: "Claude Fable 5", efforts: {"max":"max"} },
    { id: "claude-opus-5", name: "Claude Opus 5", efforts: {"max":"max"} },
    { id: "claude-sonnet-5", name: "Claude Sonnet 5", efforts: {"max":"max"} },
    { id: "claude-opus-4-8", name: "Claude Opus 4.8", efforts: {"max":"max"} },
    ],
  },
  {
    id: "gemini",
    name: "Google Gemini (OpenAI 兼容)",
    baseUrl: "https://generativelanguage.googleapis.com/v1beta/openai",
    api: "openai-completions",
    docs: "https://ai.google.dev/gemini-api/docs/openai",
    keyUrl: "https://aistudio.google.com/apikey",
    models: [
    { id: "gemini-3.1-pro-preview", name: "Gemini 3.1 Pro Preview", efforts: {"low":"LOW","high":"HIGH"} },
    { id: "gemini-3.8-flash", name: "Gemini 3.8 Flash" },
    { id: "gemini-3.5-flash", name: "Gemini 3.5 Flash" },
    { id: "gemini-2.5-pro", name: "Gemini 2.5 Pro" },
    ],
  },
  {
    id: "xai",
    name: "xAI Grok",
    baseUrl: "https://api.x.ai/v1",
    api: "openai-completions",
    docs: "https://docs.x.ai/docs/models",
    keyUrl: "https://console.x.ai",
    models: [
    { id: "grok-4.6", name: "Grok 4.6", efforts: {"low":"low","medium":"medium","high":"high"} },
    { id: "grok-4.5", name: "Grok 4.5", efforts: {"low":"low","medium":"medium","high":"high"} },
    { id: "grok-4.3", name: "Grok 4.3", efforts: {"none":"none","low":"low","medium":"medium","high":"high"} },
    ],
  },
  {
    id: "mistral",
    name: "Mistral",
    baseUrl: "https://api.mistral.ai/v1",
    api: "openai-completions",
    docs: "https://docs.mistral.ai/getting-started/models/models_overview/",
    keyUrl: "https://console.mistral.ai/api-keys",
    models: [
    { id: "mistral-large-latest", name: "Mistral Large (latest)" },
    { id: "mistral-medium-latest", name: "Mistral Medium (latest)" },
    { id: "magistral-medium-latest", name: "Magistral Medium (latest)" },
    { id: "devstral-medium-latest", name: "Devstral 2 (latest)" },
    { id: "devstral-latest", name: "Devstral 2" },
    ],
  },
  {
    id: "groq",
    name: "Groq",
    baseUrl: "https://api.groq.com/openai/v1",
    api: "openai-completions",
    docs: "https://console.groq.com/docs/models",
    keyUrl: "https://console.groq.com/keys",
    models: [
    { id: "qwen/qwen3.8-27b", name: "Qwen3.8 27B", efforts: {"none":"none","low":"low","medium":"medium","high":"high"} },
    { id: "qwen/qwen3.6-27b", name: "Qwen3.6 27B", efforts: {"none":"none","high":"default"} },
    { id: "llama-3.3-70b-versatile", name: "Llama 3.3 70B" },
    { id: "llama-3.1-8b-instant", name: "Llama 3.1 8B" },
    { id: "openai/gpt-oss-120b", name: "GPT OSS 120B", efforts: {"low":"low","medium":"medium","high":"high"} },
    ],
  },
  {
    id: "together",
    name: "Together AI",
    baseUrl: "https://api.together.xyz/v1",
    api: "openai-completions",
    docs: "https://docs.together.ai/docs/serverless-models",
    keyUrl: "https://api.together.ai/settings/api-keys",
    models: [
    { id: "zai-org/GLM-5.3", name: "GLM-5.3" },
    { id: "zai-org/GLM-5.3-Flash", name: "GLM-5.3-Flash" },
    { id: "zai-org/GLM-5.2", name: "GLM-5.2" },
    { id: "google/gemma-4-31B-it", name: "Gemma 4 31B Instruct" },
    { id: "deepseek-ai/DeepSeek-V4-Pro-0813", name: "DeepSeek V4 Pro 0813" },
    ],
  },
  {
    id: "fireworks",
    name: "Fireworks AI",
    baseUrl: "https://api.fireworks.ai/inference/v1",
    api: "openai-completions",
    docs: "https://fireworks.ai/models",
    keyUrl: "https://fireworks.ai/account/api-keys",
    models: [
    { id: "accounts/fireworks/models/glm-5p2", name: "GLM 5.2", efforts: {"none":"none","low":"high","medium":"high","high":"high","max":"max"} },
    { id: "accounts/fireworks/models/glm-5p3", name: "GLM 5.3", efforts: {"low":"low","high":"high","max":"max"} },
    { id: "accounts/fireworks/models/glm-5p3-flash", name: "GLM 5.3 Flash", efforts: {"low":"low","high":"high","max":"max"} },
    { id: "accounts/fireworks/models/deepseek-v4-flash-0731", name: "DeepSeek V4 Flash 0731" },
    { id: "accounts/fireworks/models/deepseek-v4-flash-vision-exp", name: "DeepSeek V4 Flash Vision Exp" },
    ],
  },
  {
    id: "deepinfra",
    name: "DeepInfra",
    baseUrl: "https://api.deepinfra.com/v1/openai",
    api: "openai-completions",
    docs: "https://deepinfra.com/models",
    keyUrl: "https://deepinfra.com/dash/api_keys",
    models: [
    { id: "deepseek-ai/DeepSeek-V3.1", name: "DeepSeek V3.1" },
    { id: "meta-llama/Llama-4-Maverick-17B-128E-Instruct-FP8", name: "Llama 4 Maverick" },
    ],
  },
  {
    id: "novita",
    name: "Novita AI",
    baseUrl: "https://api.novita.ai/v3/openai",
    api: "openai-completions",
    docs: "https://novita.ai/model-api/product/llm-api",
    keyUrl: "https://novita.ai/settings/key-management",
    models: [
    { id: "deepseek/deepseek-v3.1", name: "DeepSeek V3.1" },
    { id: "qwen/qwen3-coder-480b-a35b-instruct", name: "Qwen3 Coder 480B" },
    ],
  },
  {
    id: "siliconflow",
    name: "硅基流动 SiliconFlow",
    baseUrl: "https://api.siliconflow.cn/v1",
    api: "openai-completions",
    docs: "https://docs.siliconflow.cn/cn/userguide/introduction",
    keyUrl: "https://cloud.siliconflow.cn/account/ak",
    models: [
    { id: "deepseek-ai/DeepSeek-V3.2-Exp", name: "DeepSeek V3.2", efforts: {"low":"low","high":"high"} },
    { id: "Qwen/Qwen3-235B-A22B-Thinking-2507", name: "Qwen3 235B Thinking" },
    { id: "zai-org/GLM-4.6", name: "GLM-4.6", efforts: {"low":"low","medium":"medium","high":"high"} },
    ],
  },
  {
    id: "moonshot",
    name: "月之暗面 Kimi（国内）",
    baseUrl: "https://api.moonshot.cn/v1",
    api: "openai-completions",
    docs: "https://platform.moonshot.cn/docs",
    keyUrl: "https://platform.moonshot.cn/console/api-keys",
    models: [
    { id: "kimi-k3", name: "Kimi K3", efforts: {"low":"low","high":"high","max":"max"} },
    { id: "kimi-k2.7-code", name: "Kimi K2.7 Code" },
    { id: "kimi-k2.7-code-highspeed", name: "Kimi K2.7 Code HighSpeed" },
    { id: "kimi-k2.6", name: "Kimi K2.6" },
    { id: "kimi-k2.5", name: "Kimi K2.5" },
    { id: "kimi-k2-0711-preview", name: "Kimi K2 0711" },
    { id: "kimi-k2-0905-preview", name: "Kimi K2 0905" },
    { id: "kimi-k2-thinking", name: "Kimi K2 Thinking" },
    { id: "kimi-k2-thinking-turbo", name: "Kimi K2 Thinking Turbo" },
    { id: "kimi-k2-turbo-preview", name: "Kimi K2 Turbo" },
    ],
  },
  {
    id: "zhipu",
    name: "智谱 GLM（国内）",
    baseUrl: "https://open.bigmodel.cn/api/paas/v4",
    api: "openai-completions",
    docs: "https://docs.bigmodel.cn/cn/guide/models/text/glm-4.6",
    keyUrl: "https://bigmodel.cn/usercenter/apikeys",
    models: [
    { id: "glm-5.3", name: "GLM-5.3", efforts: {"low":"low","high":"high","max":"max"} },
    { id: "glm-5.3-flash", name: "GLM-5.3-Flash", efforts: {"low":"low","high":"high","max":"max"} },
    { id: "glm-5.3-highspeed", name: "GLM-5.3 Highspeed", efforts: {"low":"low","high":"high","max":"max"} },
    { id: "glm-5.2", name: "GLM-5.2", efforts: {"none":"none","high":"high","max":"max"} },
    { id: "glm-5.2-highspeed", name: "GLM-5.2 Highspeed", efforts: {"none":"none","high":"high","max":"max"} },
    ],
  },
  {
    id: "minimax",
    name: "MiniMax",
    baseUrl: "https://api.minimaxi.com/anthropic",
    api: "anthropic-messages",
    docs: "https://platform.minimaxi.com/document/guides/chat-model/V2",
    keyUrl: "https://platform.minimaxi.com/user-center/basic-information/interface-key",
    models: [
    { id: "MiniMax-M3", name: "MiniMax-M3" },
    { id: "MiniMax-M2.7", name: "MiniMax-M2.7" },
    { id: "MiniMax-M2.7-highspeed", name: "MiniMax-M2.7-highspeed" },
    ],
  },
  {
    id: "dashscope",
    name: "阿里云百炼 Qwen",
    baseUrl: "https://dashscope.aliyuncs.com/compatible-mode/v1",
    api: "openai-completions",
    docs: "https://help.aliyun.com/zh/model-studio/models",
    keyUrl: "https://bailian.console.aliyun.com/?apiKey=1",
    models: [
    { id: "qwen3-max", name: "Qwen3 Max" },
    { id: "qwen3-coder-plus", name: "Qwen3 Coder Plus" },
    { id: "qwen-plus", name: "Qwen Plus" },
    ],
  },
  {
    id: "qianfan",
    name: "百度千帆（文心）",
    baseUrl: "https://qianfan.baidubce.com/v2",
    api: "openai-completions",
    docs: "https://cloud.baidu.com/doc/qianfan-api/s/3m7of64lb",
    keyUrl: "https://console.bce.baidu.com/iam/#/iam/apikey/list",
    models: [
    { id: "ernie-5.0", name: "文心 5.0" },
    { id: "ernie-x1.1", name: "文心 X1.1" },
    ],
  },
  {
    id: "hunyuan",
    name: "腾讯混元",
    baseUrl: "https://api.hunyuan.cloud.tencent.com/v1",
    api: "openai-completions",
    docs: "https://cloud.tencent.com/document/product/1729/111007",
    keyUrl: "https://console.cloud.tencent.com/hunyuan/api-key",
    models: [
    { id: "hunyuan-turbos-latest", name: "混元 TurboS" },
    { id: "hunyuan-t1-latest", name: "混元 T1" },
    ],
  },
  {
    id: "ark",
    name: "火山方舟（豆包）",
    baseUrl: "https://ark.cn-beijing.volces.com/api/v3",
    api: "openai-completions",
    docs: "https://www.volcengine.com/docs/82379/1330310",
    keyUrl: "https://console.volcengine.com/ark/region:ark+cn-beijing/apiKey",
    models: [
    { id: "doubao-seed-1-6-250615", name: "豆包 Seed 1.6" },
    { id: "doubao-seed-1-6-thinking-250715", name: "豆包 Seed 1.6 Thinking" },
    ],
  },
  {
    id: "stepfun-step-plan",
    name: "StepFun Step Plan（国内）",
    baseUrl: "https://api.stepfun.com/step_plan/v1",
    api: "openai-completions",
    docs: "https://platform.stepfun.com/docs/zh/step-plan/quick-start",
    keyUrl: "https://platform.stepfun.com/account-overview",
    models: [
    { id: "step-5-preview", name: "Step 5 Preview", efforts: {"low":"low","medium":"medium","high":"high"} },
    { id: "step-3.7-flash", name: "Step 3.7 Flash", efforts: {"low":"low","medium":"medium","high":"high"} },
    { id: "step-3.5-flash", name: "Step 3.5 Flash", efforts: {"low":"low","medium":"medium","high":"high"} },
    { id: "step-3.5-flash-2603", name: "Step 3.5 Flash 2603", efforts: {"low":"low","medium":"medium","high":"high"} },
    ],
  },
  {
    id: "cerebras",
    name: "Cerebras",
    baseUrl: "https://api.cerebras.ai/v1",
    api: "openai-completions",
    docs: "https://cloud.cerebras.ai",
    keyUrl: "https://cloud.cerebras.ai/platform/api-keys",
    models: [
    { id: "gemma-4-31b", name: "Gemma 4 31B IT", efforts: {"none":"none","low":"low","medium":"medium","high":"high"} },
    { id: "gpt-oss-120b", name: "GPT OSS 120B", efforts: {"low":"low","medium":"medium","high":"high"} },
    ],
  },
  {
    id: "nvidia",
    name: "NVIDIA NIM",
    baseUrl: "https://integrate.api.nvidia.com/v1",
    api: "openai-completions",
    docs: "https://build.nvidia.com",
    keyUrl: "https://build.nvidia.com/settings/api-keys",
    models: [
    { id: "moonshotai/kimi-k3", name: "Kimi K3" },
    { id: "deepseek-ai/deepseek-v4-flash-0731", name: "DeepSeek V4 Flash 0731", efforts: {"high":"high","max":"max"} },
    { id: "deepseek-ai/deepseek-v4-pro-0813", name: "DeepSeek V4 Pro 0813", efforts: {"high":"high","max":"max"} },
    { id: "minimaxai/minimax-m3", name: "MiniMax-M3" },
    ],
  },
  {
    id: "baseten",
    name: "Baseten",
    baseUrl: "https://inference.baseten.co/v1",
    api: "openai-completions",
    docs: "https://docs.baseten.co",
    keyUrl: "https://app.baseten.co/settings/api_keys",
    models: [
    { id: "deepseek-ai/DeepSeek-V4-Flash-0731", name: "DeepSeek V4 Flash 0731", efforts: {"none":"none","low":"low","medium":"medium","high":"high","max":"max"} },
    { id: "deepseek-ai/DeepSeek-V4-Pro", name: "DeepSeek V4 Pro", efforts: {"none":"none","low":"low","medium":"medium","high":"high","max":"max"} },
    { id: "deepseek-ai/DeepSeek-V4-Pro-0813", name: "DeepSeek V4 Pro 0813", efforts: {"none":"none","low":"low","high":"high","max":"max"} },
    { id: "moonshotai/Kimi-K3", name: "Kimi K3", efforts: {"none":"none","low":"low","high":"high","max":"max"} },
    ],
  },
  {
    id: "huggingface",
    name: "HuggingFace Router",
    baseUrl: "https://router.huggingface.co/v1",
    api: "openai-completions",
    docs: "https://huggingface.co/docs/inference-providers",
    keyUrl: "https://huggingface.co/settings/tokens",
    models: [
    { id: "XiaomiMiMo/MiMo-V2.5-Pro", name: "MiMo-V2.5-Pro", efforts: {"none":"none","low":"low","medium":"medium","high":"high"} },
    { id: "deepseek-ai/DeepSeek-V4-Flash", name: "DeepSeek V4 Flash" },
    { id: "deepseek-ai/DeepSeek-V4-Flash-0731", name: "DeepSeek V4 Flash 0731", efforts: {"high":"high","max":"max"} },
    { id: "deepseek-ai/DeepSeek-V4-Flash-Vision-Exp", name: "DeepSeek V4 Flash Vision Exp", efforts: {"low":"low","high":"high","max":"max"} },
    ],
  },
  {
    id: "opencode-go",
    name: "OpenCode Zen Go",
    baseUrl: "https://opencode.ai/zen/go/v1",
    api: "openai-responses",
    docs: "https://opencode.ai/docs/zen",
    keyUrl: "https://opencode.ai/auth",
    models: [
    { id: "gpt-5.6-luna", name: "GPT-5.6 Luna", efforts: {"low":"low","medium":"medium","high":"high","max":"max"} },
    { id: "kimi-k3", name: "Kimi K3", efforts: {"max":"max"} },
    { id: "mimo-v2.5-pro", name: "MiMo V2.5 Pro" },
    { id: "muse-spark-1.2-contributor", name: "Muse Spark 1.2 Contributor", efforts: {"low":"low","medium":"medium","high":"high"} },
    ],
  },
  {
    id: "opencode-zen",
    name: "OpenCode Zen",
    baseUrl: "https://opencode.ai/zen/v1",
    api: "openai-responses",
    docs: "https://opencode.ai/docs/zen",
    keyUrl: "https://opencode.ai/auth",
    models: [
    { id: "gpt-5.4-pro", name: "GPT-5.4 Pro", efforts: {"medium":"medium","high":"high"} },
    { id: "gpt-5.5", name: "GPT-5.5", efforts: {"low":"low","medium":"medium","high":"high"} },
    { id: "gpt-5.5-pro", name: "GPT-5.5 Pro", efforts: {"medium":"medium","high":"high"} },
    { id: "gpt-5.6-luna", name: "GPT-5.6 Luna", efforts: {"low":"low","medium":"medium","high":"high","max":"max"} },
    ],
  },
  {
    id: "qwen-token-plan-cn",
    name: "阿里云百炼 Token Plan（国内）",
    baseUrl: "https://token-plan.cn-beijing.maas.aliyuncs.com/compatible-mode/v1",
    api: "openai-completions",
    docs: "https://help.aliyun.com/zh/model-studio/",
    keyUrl: "https://bailian.console.aliyun.com/",
    models: [
    { id: "deepseek-v4-flash", name: "DeepSeek V4 Flash", efforts: {"high":"high","max":"max"} },
    { id: "deepseek-v4-flash-0731", name: "DeepSeek V4 Flash 0731", efforts: {"high":"high","max":"max"} },
    { id: "deepseek-v4-pro", name: "DeepSeek V4 Pro", efforts: {"high":"high","max":"max"} },
    { id: "deepseek-v4-pro-0813", name: "DeepSeek V4 Pro 0813", efforts: {"high":"high","max":"max"} },
    { id: "qwen3.7-max", name: "Qwen3.7 Max" },
    { id: "qwen3.8-max", name: "Qwen3.8 Max", efforts: {"low":"low","medium":"medium"} },
    { id: "glm-5", name: "GLM-5", efforts: {"high":"high","max":"max"} },
    { id: "deepseek-v4.1-flash", name: "DeepSeek V4.1 Flash", efforts: {"low":"low","high":"high","max":"max"} },
    { id: "qwen3.8-max-preview", name: "Qwen3.8 Max Preview", efforts: {"low":"low","medium":"medium"} },
    { id: "kimi-k2.6", name: "Kimi K2.6" },
    { id: "kimi-k2.5", name: "Kimi K2.5" },
    { id: "qwen3.6-flash", name: "Qwen3.6 Flash" },
    { id: "MiniMax-M2.5", name: "MiniMax-M2.5" },
    { id: "qwen3.8-flash", name: "Qwen3.8 Flash", efforts: {"low":"low","medium":"medium"} },
    { id: "glm-5.2", name: "GLM-5.2", efforts: {"high":"high","max":"max"} },
    { id: "glm-5.1", name: "GLM-5.1", efforts: {"high":"high","max":"max"} },
    { id: "qwen3.6-plus", name: "Qwen3.6 Plus" },
    { id: "deepseek-v3.2", name: "DeepSeek V3.2" },
    { id: "glm-5.3", name: "GLM-5.3", efforts: {"low":"low","high":"high","max":"max"} },
    { id: "kimi-k2.7-code", name: "Kimi K2.7 Code" },
    { id: "qwen3.7-plus", name: "Qwen3.7 Plus" },
    ],
  },
  {
    id: "zai-coding-cn",
    name: "智谱 Coding Plan（国内）",
    baseUrl: "https://open.bigmodel.cn/api/coding/paas/v4",
    api: "openai-completions",
    docs: "https://docs.bigmodel.cn/",
    keyUrl: "https://bigmodel.cn/usercenter/apikeys",
    models: [
    { id: "glm-5.2", name: "GLM-5.2", efforts: {"none":"none","high":"high","max":"max"} },
    { id: "glm-5.2-highspeed", name: "GLM-5.2 Highspeed", efforts: {"none":"none","high":"high","max":"max"} },
    { id: "glm-5.3", name: "GLM-5.3", efforts: {"low":"low","high":"high","max":"max"} },
    { id: "glm-5.3-flash", name: "GLM-5.3-Flash", efforts: {"low":"low","high":"high","max":"max"} },
    { id: "glm-5.3-highspeed", name: "GLM-5.3 Highspeed", efforts: {"low":"low","high":"high","max":"max"} },
    { id: "glm-4.7", name: "GLM-4.7" },
    { id: "glm-5-turbo", name: "GLM-5-Turbo" },
    { id: "glm-4.6v", name: "GLM-4.6V" },
    { id: "glm-5.1", name: "GLM-5.1" },
    { id: "glm-5v-turbo", name: "GLM-5V-Turbo" },
    ],
  },
  {
    id: "kimi-coding",
    name: "Kimi Coding Plan",
    baseUrl: "https://api.kimi.com/coding/v1",
    api: "anthropic-messages",
    docs: "https://platform.moonshot.cn/docs",
    keyUrl: "https://platform.moonshot.cn/console/api-keys",
    models: [
    { id: "k3", name: "Kimi K3", efforts: {"low":"low","high":"high","max":"max"} },
    { id: "k3-256k", name: "Kimi K3-256K", efforts: {"low":"low","high":"high","max":"max"} },
    { id: "kimi-for-coding", name: "Kimi K2.7 Code" },
    { id: "kimi-for-coding-highspeed", name: "Kimi For Coding HighSpeed" },
    ],
  },
  {
    id: "xiaomi",
    name: "小米 MiMo",
    baseUrl: "https://api.xiaomimimo.com/v1",
    api: "openai-completions",
    docs: "https://platform.xiaomimimo.com/",
    keyUrl: "https://platform.xiaomimimo.com/",
    models: [
    { id: "mimo-v2.5", name: "MiMo-V2.5" },
    { id: "mimo-v2.5-pro", name: "MiMo-V2.5-Pro" },
    { id: "mimo-v2.5-pro-ultraspeed", name: "MiMo-V2.5-Pro-UltraSpeed" },
    ],
  },
  {
    id: "ant-ling",
    name: "Ant Ling",
    baseUrl: "https://api.ant-ling.com/v1",
    api: "openai-completions",
    docs: "https://www.ant-ling.com/",
    keyUrl: "https://www.ant-ling.com/",
    models: [
    { id: "Ring-2.6-1T", name: "Ring 2.6 1T", efforts: {"high":"high"} },
    { id: "Ling-2.6-1T", name: "Ling 2.6 1T" },
    { id: "Ling-2.6-flash", name: "Ling 2.6 Flash" },
    ],
  },
  {
    id: "vercel-ai-gateway",
    name: "Vercel AI Gateway",
    baseUrl: "https://ai-gateway.vercel.sh",
    api: "anthropic-messages",
    docs: "https://vercel.com/docs/ai-gateway",
    keyUrl: "https://vercel.com/dashboard",
    models: [
    { id: "anthropic/claude-opus-5", name: "Claude Opus 5", efforts: {"max":"max"} },
    { id: "anthropic/claude-fable-5.1", name: "Claude Fable 5.1", efforts: {"max":"max"} },
    { id: "anthropic/claude-sonnet-5", name: "Claude Sonnet 5", efforts: {"max":"max"} },
    { id: "openai/gpt-5.6-sol", name: "GPT 5.6 Sol" },
    { id: "openai/gpt-5.6-luna", name: "GPT 5.6 Luna" },
    { id: "google/gemini-3.1-pro-preview", name: "Gemini 3.1 Pro Preview" },
    { id: "google/gemini-3.8-flash", name: "Gemini 3.8 Flash" },
    { id: "deepseek/deepseek-v4-flash", name: "DeepSeek V4 Flash" },
    { id: "moonshotai/kimi-k3", name: "Kimi K3" },
    { id: "xiaomi/mimo-v2.5-pro", name: "MiMo V2.5 Pro" },
    { id: "spacexai/grok-4.20-reasoning", name: "Grok 4.20 Reasoning" },
    { id: "alibaba/qwen3.8-max", name: "Qwen 3.8 Max" },
    ],
  },
  {
    id: "minimax-cn-coding-plan",
    name: "MiniMax Coding Plan（国内）",
    baseUrl: "https://api.minimax.cn/anthropic/v1",
    api: "anthropic-messages",
    docs: "https://platform.minimaxi.com/document",
    keyUrl: "https://platform.minimaxi.com/user-center/basic-information/interface-key",
    models: [
    { id: "MiniMax-M3", name: "MiniMax M3" },
    { id: "MiniMax-M2.7", name: "MiniMax M2.7" },
    { id: "MiniMax-M2.5", name: "MiniMax M2.5" },
    { id: "MiniMax-M2.1", name: "MiniMax M2.1" },
    ],
  },
  {
    id: "longcat",
    name: "LongCat（美团）",
    baseUrl: "https://api.longcat.chat/openai",
    api: "openai-completions",
    docs: "https://longcat.chat/platform/docs",
    keyUrl: "https://longcat.chat/platform/api_keys",
    models: [
    { id: "LongCat-2.0", name: "LongCat 2.0" },
    ],
  },
  {
    id: "volcengine-agent-plan",
    name: "火山方舟 Agent Plan",
    baseUrl: "https://ark.cn-beijing.volces.com/api/plan/v3",
    api: "openai-responses",
    docs: "https://www.volcengine.com/docs/82379",
    keyUrl: "https://console.volcengine.com/ark",
    models: [
    { id: "ark-code-latest", name: "Ark Code Latest", efforts: {"low":"low","medium":"medium","high":"high"} },
    { id: "deepseek-v4.1-flash", name: "DeepSeek V4.1 Flash", efforts: {"none":"none","low":"low","high":"high","max":"max"} },
    { id: "glm-5.3", name: "GLM-5.3", efforts: {"low":"low","high":"high","max":"max"} },
    { id: "kimi-k3", name: "Kimi K3", efforts: {"low":"low","high":"high","max":"max"} },
    { id: "deepseek-v4-pro", name: "DeepSeek V4 Pro", efforts: {"none":"none","high":"high","max":"max"} },
    { id: "deepseek-v4-flash", name: "DeepSeek V4 Flash", efforts: {"none":"none","low":"low","high":"high","max":"max"} },
    { id: "kimi-k2.8-preview", name: "Kimi K2.8 Preview", efforts: {"low":"low","high":"high","max":"max"} },
    ],
  },
  {
    id: "cline-pass",
    name: "ClinePass",
    baseUrl: "https://api.cline.bot/api/v1",
    api: "openai-completions",
    docs: "https://cline.bot",
    keyUrl: "https://cline.bot/dashboard",
    models: [
    { id: "cline-pass/mimo-v2.6-pro", name: "MiMo V2.6 Pro", efforts: {"none":"none","low":"low","medium":"medium","high":"high"} },
    { id: "cline-pass/qwen3.7-max", name: "Qwen3.7 Max" },
    { id: "cline-pass/mimo-v2.5", name: "MiMo V2.5" },
    { id: "cline-pass/glm-5.3-flash", name: "GLM-5.3 Flash", efforts: {"low":"low","high":"high","max":"max"} },
    { id: "cline-pass/qwen3.8-max", name: "Qwen3.8 Max", efforts: {"none":"none","low":"low","medium":"medium"} },
    { id: "cline-pass/kimi-k3", name: "Kimi K3", efforts: {"none":"none","low":"low","high":"high","max":"max"} },
    { id: "cline-pass/deepseek-v4.1-flash", name: "DeepSeek V4.1 Flash", efforts: {"none":"none","low":"low","high":"high","max":"max"} },
    { id: "cline-pass/kimi-k2.6", name: "Kimi K2.6" },
    { id: "cline-pass/mimo-v2.5-pro", name: "MiMo V2.5 Pro" },
    { id: "cline-pass/mimo-v2.6-flash", name: "MiMo V2.6 Flash", efforts: {"none":"none","low":"low","medium":"medium","high":"high"} },
    { id: "cline-pass/minimax-m3", name: "MiniMax M3" },
    { id: "cline-pass/glm-5.2", name: "GLM 5.2", efforts: {"none":"none","high":"high","max":"max"} },
    { id: "cline-pass/deepseek-v4-pro", name: "DeepSeek V4 Pro", efforts: {"none":"none","high":"high","max":"max"} },
    { id: "cline-pass/muse-spark-1.3-contributor", name: "Muse Spark 1.3 Contributor", efforts: {"low":"low","medium":"medium","high":"high"} },
    { id: "cline-pass/glm-5.3", name: "GLM 5.3", efforts: {"low":"low","high":"high","max":"max"} },
    { id: "cline-pass/kimi-k2.7-code", name: "Kimi K2.7 Code" },
    { id: "cline-pass/qwen3.7-plus", name: "Qwen3.7 Plus" },
    { id: "cline-pass/deepseek-v4-flash", name: "DeepSeek V4 Flash", efforts: {"none":"none","low":"low","high":"high","max":"max"} },
    ],
  },
  {
    id: "zenmux",
    name: "ZenMux",
    baseUrl: "https://zenmux.ai/api/v1",
    api: "openai-completions",
    docs: "https://zenmux.ai",
    keyUrl: "https://zenmux.ai",
    models: [
    { id: "openai/gpt-5.4-pro", name: "GPT-5.4 Pro", efforts: {"medium":"medium","high":"high"} },
    { id: "openai/gpt-5.5-pro", name: "GPT-5.5 Pro", efforts: {"medium":"medium","high":"high"} },
    { id: "xiaomi/mimo-v2.5-pro", name: "MiMo-V2.5-Pro" },
    { id: "minimax/minimax-m3", name: "MiniMax-M3" },
    { id: "google/gemini-3.1-pro-preview", name: "Gemini 3.1 Pro Preview", efforts: {"low":"low","medium":"medium","high":"high"} },
    { id: "google/gemini-2.5-pro", name: "Gemini 2.5 Pro", efforts: {"low":"low","medium":"medium","high":"high"} },
    { id: "deepseek/deepseek-v4-pro", name: "DeepSeek V4 Pro", efforts: {"low":"low","medium":"medium","high":"high"} },
    { id: "xiaomi/mimo-v2-pro", name: "MiMo V2 Pro" },
    { id: "qwen/qwen3.7-max", name: "Qwen3.7 Max" },
    { id: "moonshotai/kimi-k2-thinking", name: "Kimi K2 Thinking" },
    { id: "moonshotai/kimi-k2-thinking-turbo", name: "Kimi K2 Thinking Turbo" },
    { id: "qwen/qwen3-max", name: "Qwen3-Max-Thinking" },
    { id: "minimax/minimax-m2.5-lightning", name: "MiniMax M2.5 highspeed" },
    { id: "anthropic/claude-opus-4.6", name: "Claude Opus 4.6", efforts: {"low":"low","medium":"medium","high":"high"} },
    { id: "anthropic/claude-opus-4.7", name: "Claude Opus 4.7", efforts: {"low":"low","medium":"medium","high":"high"} },
    { id: "deepseek/deepseek-v4-flash", name: "DeepSeek V4 Flash", efforts: {"low":"low","medium":"medium","high":"high"} },
    { id: "z-ai/glm-5.3-flash", name: "GLM 5.3 Flash", efforts: {"low":"low","high":"high","max":"max"} },
    { id: "z-ai/glm-5.3-flashx", name: "GLM 5.3 FlashX", efforts: {"low":"low","high":"high","max":"max"} },
    ],
  },
  {
    id: "poe",
    name: "Poe",
    baseUrl: "https://api.poe.com/v1",
    api: "openai-completions",
    docs: "https://poe.com",
    keyUrl: "https://poe.com",
    models: [
    { id: "google/gemini-2.5-pro", name: "Gemini-2.5-Pro" },
    { id: "openai/gpt-5.4-pro", name: "GPT-5.4-Pro", efforts: {"medium":"medium","high":"high"} },
    { id: "google/gemini-3-pro", name: "Gemini-3-Pro" },
    { id: "empiriolabs/deepseek-v4-pro-el", name: "DeepSeek-V4-Pro-EL" },
    { id: "openai/gpt-5.5-pro", name: "GPT-5.5-Pro", efforts: {"medium":"medium","high":"high"} },
    { id: "novita/kimi-k2-thinking", name: "Kimi K2 THINKING" },
    { id: "novita/minimax-m2.1", name: "Minimax M2.1" },
    { id: "openai/o3-pro", name: "O3 PRO", efforts: {"low":"low","medium":"medium","high":"high"} },
    { id: "openai/o1-pro", name: "O1 PRO", efforts: {"low":"low","medium":"medium","high":"high"} },
    { id: "anthropic/claude-opus-4.7", name: "Claude-Opus-4.7", efforts: {"none":"none","low":"low","medium":"medium","high":"high","max":"max"} },
    { id: "anthropic/claude-opus-4.8", name: "Claude-Opus-4.8", efforts: {"none":"none","low":"low","medium":"medium","high":"high","max":"max"} },
    { id: "empiriolabs/deepseek-v4-flash-el", name: "DeepSeek-V4-Flash-EL" },
    { id: "novita/kimi-k2.6", name: "Kimi-K2.6" },
    { id: "xai/grok-4", name: "Grok-4" },
    { id: "novita/glm-5", name: "GLM-5" },
    { id: "novita/glm-4.7", name: "Glm 4.7" },
    { id: "openai/o4-mini", name: "O4 MINI", efforts: {"low":"low","medium":"medium","high":"high"} },
    { id: "openai/o3-mini", name: "O3 MINI", efforts: {"low":"low","medium":"medium","high":"high"} },
    ],
  },
  {
    id: "qiniu-ai",
    name: "七牛云 AI",
    baseUrl: "https://api.qnaigc.com/v1",
    api: "openai-completions",
    docs: "https://www.qiniu.com",
    keyUrl: "https://www.qiniu.com",
    models: [
    { id: "gemini-2.5-pro", name: "Gemini 2.5 Pro" },
    { id: "gemini-3.0-flash-preview", name: "Gemini 3.0 Flash Preview" },
    { id: "MiniMax-M1", name: "MiniMax M1" },
    { id: "qwen3-235b-a22b-thinking-2507", name: "Qwen3 235B A22B Thinking 2507" },
    { id: "minimax/minimax-m2.5", name: "Minimax/Minimax-M2.5" },
    { id: "qwen3-next-80b-a3b-thinking", name: "Qwen3 Next 80B A3B Thinking" },
    { id: "deepseek/deepseek-v3.2-exp-thinking", name: "DeepSeek/DeepSeek-V3.2-Exp-Thinking" },
    { id: "deepseek/deepseek-v3.1-terminus-thinking", name: "DeepSeek/DeepSeek-V3.1-Terminus-Thinking" },
    { id: "moonshotai/kimi-k2-thinking", name: "Kimi K2 Thinking" },
    { id: "stepfun-ai/gelab-zero-4b-preview", name: "Stepfun-Ai/Gelab Zero 4b Preview" },
    { id: "openai/gpt-5.2", name: "OpenAI/GPT-5.2" },
    { id: "mimo-v2-flash", name: "Mimo-V2-Flash" },
    { id: "xiaomi/mimo-v2-flash", name: "Xiaomi/Mimo-V2-Flash" },
    { id: "claude-4.5-sonnet", name: "Claude 4.5 Sonnet" },
    { id: "claude-4.0-sonnet", name: "Claude 4.0 Sonnet" },
    { id: "z-ai/glm-5", name: "Z-Ai/GLM 5" },
    ],
  },
  {
    id: "302ai",
    name: "302.AI",
    baseUrl: "https://api.302.ai/v1",
    api: "openai-completions",
    docs: "https://302.ai",
    keyUrl: "https://302.ai",
    models: [
    { id: "grok-4.20-beta-0309-reasoning", name: "Grok 4.20 Beta 0309 Reasoning" },
    { id: "gpt-5.6-sol-pro", name: "Gpt 5.6 Sol PRO", efforts: {"none":"none","low":"low","medium":"medium","high":"high","max":"max"} },
    { id: "gpt-5.6-luna-pro", name: "Gpt 5.6 Luna PRO", efforts: {"none":"none","low":"low","medium":"medium","high":"high","max":"max"} },
    { id: "MiniMax-M3", name: "MiniMax-M3" },
    { id: "gemini-3.5-flash-thinking", name: "Gemini 3.5 FLASH THINKING" },
    { id: "gemini-3.1-pro-preview", name: "Gemini 3.1 Pro Preview", efforts: {"low":"low","medium":"medium","high":"high"} },
    { id: "qwen3.7-max", name: "Qwen3.7 Max" },
    { id: "qwen3.8-max", name: "Qwen3.8 Max", efforts: {"low":"low","medium":"medium"} },
    { id: "claude-sonnet-4-6-thinking", name: "Claude Sonnet 4 6 THINKING" },
    { id: "claude-opus-5-thinking", name: "Claude Opus 5 THINKING" },
    { id: "kimi-k2-thinking", name: "Kimi K2 THINKING" },
    { id: "MiniMax-M2.1", name: "MiniMax-M2.1" },
    { id: "deepseek-v3.2-thinking", name: "DeepSeek-V3.2-Thinking" },
    { id: "kimi-k2-0905-preview", name: "Kimi K2 0905 PREVIEW" },
    { id: "glm-5.3-flash", name: "GLM-5.3-Flash", efforts: {"low":"low","high":"high","max":"max"} },
    { id: "grok-4.3", name: "Grok 4.3", efforts: {"none":"none","low":"low","medium":"medium","high":"high"} },
    { id: "deepseek-flash", name: "DeepSeek V4.1 Flash", efforts: {"low":"low","high":"high","max":"max"} },
    { id: "glm-5.2", name: "GLM-5.2", efforts: {"high":"high","max":"max"} },
    ],
  },
  {
    id: "tencent-coding-plan",
    name: "腾讯云 Coding Plan",
    baseUrl: "https://api.lkeap.cloud.tencent.com/coding/v3",
    api: "openai-completions",
    docs: "https://cloud.tencent.com/product/lkeap",
    keyUrl: "https://cloud.tencent.com/product/lkeap",
    models: [
    { id: "minimax-m2.5", name: "MiniMax-M2.5" },
    { id: "hunyuan-2.0-thinking", name: "Tencent HY 2.0 Think" },
    { id: "kimi-k2.5", name: "Kimi-K2.5" },
    { id: "glm-5", name: "GLM-5" },
    { id: "hunyuan-t1", name: "Hunyuan-T1" },
    ],
  },
  {
    id: "deepseek",
    name: "DeepSeek",
    baseUrl: "https://api.deepseek.com",
    api: "openai-completions",
    docs: "https://platform.deepseek.com",
    keyUrl: "https://platform.deepseek.com",
    models: [
    { id: "deepseek-v4-flash", name: "DeepSeek V4 Flash", efforts: {"low":"low","high":"high","max":"max"} },
    { id: "deepseek-v4-flash-vision-exp", name: "DeepSeek V4 Flash Vision Exp", efforts: {"low":"low","high":"high","max":"max"} },
    { id: "deepseek-v4-pro", name: "DeepSeek V4 Pro", efforts: {"high":"high","max":"max"} },
    ],
  },
  {
    id: "xiaomi-token-plan-cn",
    name: "小米 MiMo Token Plan（国内）",
    baseUrl: "https://token-plan-cn.xiaomimimo.com/v1",
    api: "openai-completions",
    docs: "https://platform.xiaomimimo.com",
    keyUrl: "https://platform.xiaomimimo.com",
    models: [
    { id: "mimo-v2.5", name: "MiMo-V2.5" },
    { id: "mimo-v2.5-pro", name: "MiMo-V2.5-Pro" },
    ],
  },
]
